//! The "book" compile: assemble the project into a print-ready PDF the way a
//! novel is set — front matter on its own pages, chapters that open on a fresh
//! page, running heads, page numbers that start at the story.
//!
//! Jqln does not typeset anything itself. It writes a [Typst](https://typst.app)
//! document — template plus prose — next to the project and, when the `typst`
//! binary is on `PATH`, runs it to produce the PDF. The `.typ` file is plain
//! text: edit it and re-run `typst compile` yourself, or tune the knobs in the
//! `[book]` table of `jqln.toml`.

mod lower;

use crate::project::{now_year, slugify, NodeId, Project};
use lower::{
    chapter_heading, content, front_matter_folder, raw, render_centered, render_prose, s, structure,
    trim_f, trim_size, Item,
};
use std::path::PathBuf;
use std::process::Command;

/// What came of a book compile.
pub enum Outcome {
    /// `typst` ran and produced a PDF.
    Pdf { typ: PathBuf, pdf: PathBuf },
    /// The `.typ` was written but `typst` is not installed.
    TypstMissing { typ: PathBuf },
    /// `typst` ran and failed; `message` is the first useful error line.
    TypstFailed { typ: PathBuf, message: String },
}

/// Compile the project to a Typst document and, if possible, a PDF.
pub fn compile_to_file(project: &mut Project) -> std::io::Result<Outcome> {
    let doc = build(project);
    let stem = slugify(&resolved_title(project));
    let typ = project.root.join(format!("{stem}.typ"));
    let pdf = project.root.join(format!("{stem}.pdf"));
    std::fs::write(&typ, doc)?;

    match Command::new("typst")
        .arg("compile")
        .arg(&typ)
        .arg(&pdf)
        .current_dir(&project.root)
        .output()
    {
        Ok(out) if out.status.success() => Ok(Outcome::Pdf { typ, pdf }),
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            let message = stderr
                .lines()
                .find(|l| l.contains("error"))
                .or_else(|| stderr.lines().next())
                .unwrap_or("typst failed")
                .trim()
                .to_string();
            Ok(Outcome::TypstFailed { typ, message })
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Outcome::TypstMissing { typ }),
        Err(e) => Err(e),
    }
}

fn resolved_title(project: &Project) -> String {
    let t = project.book.title.trim();
    if t.is_empty() { project.meta.name.clone() } else { t.to_string() }
}

// ---- document assembly -------------------------------------------------------

fn build(project: &mut Project) -> String {
    let b = project.book.clone();
    let title = resolved_title(project);
    let author = b.author.trim().to_string();
    let (w_in, h_in) = trim_size(&b.trim);

    let mut out = String::new();
    out.push_str("// Generated by jqln. Edit jqln.toml [book] and recompile, or\n");
    out.push_str("// edit this file and run `typst compile` on it yourself.\n\n");

    // --- preamble ---
    out.push_str(&format!(
        "#set document(title: {}, author: {})\n",
        s(&title),
        s(&author)
    ));
    out.push_str(&format!(
        "#set page(width: {w_in}in, height: {h_in}in, margin: (inside: 0.9in, outside: 0.65in, top: 0.8in, bottom: 0.8in))\n"
    ));
    out.push_str(&format!(
        "#set text(font: {}, size: {}pt, lang: \"en\")\n",
        s(&b.body_font),
        trim_f(b.body_size)
    ));
    out.push_str("#set par(justify: true, leading: 0.62em, first-line-indent: 1.4em, spacing: 0.62em)\n");
    out.push_str("#show heading: set text(weight: \"regular\")\n\n");

    // Chapters (and always parts) open on a fresh page, on the right when the
    // writer asked for print convention.
    let to_recto = if b.chapters_on_recto { ", to: \"odd\"" } else { "" };

    out.push_str(
        "#show heading.where(level: 1): it => {\n\
        \x20 pagebreak(weak: true, to: \"odd\")\n\
        \x20 v(28%)\n\
        \x20 set align(center)\n\
        \x20 text(size: 2em, tracking: 4pt)[#upper(it.body)]\n\
        \x20 pagebreak(weak: true)\n\
        }\n",
    );
    out.push_str(&format!(
        "#let chapsub(t) = {{ align(center, text(size: 1.3em, style: \"italic\")[#t]); v(2.4em) }}\n\
        #let scenebreak = {{ v(1em); align(center, text(tracking: 2pt)[{}]); v(1em) }}\n",
        raw(&b.scene_break)
    ));
    out.push_str(&format!(
        "#show heading.where(level: 2): it => {{\n\
        \x20 pagebreak(weak: true{to_recto})\n\
        \x20 v(16%)\n\
        \x20 set align(center)\n\
        \x20 block(text(size: 1.05em, tracking: 3pt)[#upper(it.body)])\n\
        \x20 v(2.4em)\n\
        }}\n\n"
    ));

    // --- front matter ---
    for page in front_matter(project) {
        out.push_str(&page);
        out.push('\n');
    }

    // --- body ---
    out.push_str("#pagebreak(to: \"odd\")\n");
    if b.running_heads && !author.is_empty() {
        out.push_str(&format!(
            "#set page(header: context {{\n\
            \x20 let hs = query(heading).filter(h => h.location().page() == here().page())\n\
            \x20 if hs.len() != 0 {{ return }}\n\
            \x20 set text(size: 0.82em, style: \"italic\")\n\
            \x20 set align(center)\n\
            \x20 if calc.odd(here().page()) [{}] else [{}]\n\
            }})\n",
            content(&title),
            content(&author),
        ));
    }
    out.push_str("#set page(numbering: \"1\", number-align: center)\n");
    out.push_str("#counter(page).update(1)\n\n");

    let mut chapter = 0u32;
    for item in structure(project) {
        match item {
            Item::Part { title } => {
                out.push_str(&format!("= {}\n\n", raw(&title)));
            }
            Item::Chapter { title, scenes } => {
                chapter += 1;
                out.push_str(&format!("== {}\n", raw(&chapter_heading(&project.book, chapter))));
                if let Some(sub) = title {
                    out.push_str(&format!("#chapsub[{}]\n", raw(&sub)));
                }
                out.push('\n');
                for (i, scene) in scenes.iter().enumerate() {
                    if i > 0 {
                        out.push_str("#scenebreak\n\n");
                    }
                    let body = project.body(scene);
                    out.push_str(&render_prose(&body));
                    out.push('\n');
                }
                out.push('\n');
            }
        }
    }

    out
}

// ---- front matter -----------------------------------------------------------

#[derive(PartialEq)]
enum FrontKind {
    Title,
    Copyright,
    Dedication,
    Other,
}

fn classify(title: &str) -> FrontKind {
    let t = title.to_lowercase();
    if t.contains("copyright") {
        FrontKind::Copyright
    } else if t.contains("dedication") {
        FrontKind::Dedication
    } else if t.contains("title") {
        FrontKind::Title
    } else {
        FrontKind::Other
    }
}

fn front_matter(project: &mut Project) -> Vec<String> {
    let b = project.book.clone();
    let title = resolved_title(project);
    let author = if b.author.trim().is_empty() { None } else { Some(b.author.trim().to_string()) };
    let year = if b.copyright_year == 0 { now_year() } else { b.copyright_year };
    let holder = {
        let h = b.copyright_holder.trim();
        if h.is_empty() { author.clone().unwrap_or_else(|| title.clone()) } else { h.to_string() }
    };

    // Collect authored front-matter documents in binder order.
    let docs: Vec<(NodeId, String, FrontKind)> = match front_matter_folder(project) {
        Some(fm) => project
            .text_descendants(&fm)
            .into_iter()
            .filter(|id| *id != fm)
            .map(|id| {
                let t = project.nodes.get(&id).map(|n| n.title.clone()).unwrap_or_default();
                let k = classify(&t);
                (id, t, k)
            })
            .collect(),
        None => Vec::new(),
    };

    let find = |kind: FrontKind| docs.iter().find(|(_, _, k)| *k == kind).map(|(id, t, _)| (id.clone(), t.clone()));
    let used: Vec<NodeId> = [FrontKind::Title, FrontKind::Copyright, FrontKind::Dedication]
        .into_iter()
        .filter_map(|k| find(k).map(|(id, _)| id))
        .collect();

    let mut pages = Vec::new();

    // 1. Title page.
    match find(FrontKind::Title) {
        Some((id, t)) => pages.push(custom_page(&project.body(&id), &t, true)),
        None => pages.push(gen_title_page(&title, &b.subtitle, author.as_deref(), &b.publisher)),
    }
    // 2. Copyright page.
    match find(FrontKind::Copyright) {
        Some((id, _)) => pages.push(custom_page(&project.body(&id), "", false)),
        None => pages.push(gen_copyright_page(&title, author.as_deref(), year, &holder, &b.rights, &b.publisher)),
    }
    // 3. Dedication.
    match find(FrontKind::Dedication) {
        Some((id, _)) => pages.push(gen_dedication_page_raw(&project.body(&id))),
        None if !b.dedication.trim().is_empty() => {
            pages.push(gen_dedication_page(&b.dedication))
        }
        None => {}
    }
    // 4. Everything else the writer authored, in order.
    let rest: Vec<(NodeId, String)> = docs
        .iter()
        .filter(|(id, _, _)| !used.contains(id))
        .map(|(id, t, _)| (id.clone(), t.clone()))
        .collect();
    for (id, t) in rest {
        pages.push(custom_page(&project.body(&id), &t, true));
    }

    pages
}

fn page_wrap(body: &str) -> String {
    format!("#page(numbering: none, header: none, footer: none)[\n{body}\n]\n")
}

fn gen_title_page(title: &str, subtitle: &str, author: Option<&str>, publisher: &str) -> String {
    let mut b = String::new();
    b.push_str("#set align(center)\n#v(3fr)\n");
    b.push_str(&format!("#text(size: 2.4em, weight: \"bold\")[{}]\n", content(title)));
    if !subtitle.trim().is_empty() {
        b.push_str(&format!("#v(1em)\n#text(size: 1.3em, style: \"italic\")[{}]\n", content(subtitle)));
    }
    b.push_str("#v(1fr)\n");
    if let Some(a) = author {
        b.push_str(&format!("#text(size: 1.15em)[{}]\n", content(a)));
    }
    b.push_str("#v(3fr)\n");
    if !publisher.trim().is_empty() {
        b.push_str(&format!("#text(size: 0.9em)[{}]\n", content(publisher)));
    }
    page_wrap(&b)
}

fn gen_copyright_page(
    title: &str,
    author: Option<&str>,
    year: u32,
    holder: &str,
    rights: &str,
    publisher: &str,
) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("{} \\", content(title)));
    if let Some(a) = author {
        lines.push(format!("{} \\", content(a)));
    }
    lines.push("#v(1em)".to_string());
    lines.push(format!("Copyright © {year} {} \\", content(holder)));
    if !rights.trim().is_empty() {
        lines.push(format!("{} \\", content(rights)));
    }
    lines.push("#v(1em)".to_string());
    lines.push("This is a work of fiction. Names, characters, places and incidents are the \\".to_string());
    lines.push("product of the author's imagination or are used fictitiously. \\".to_string());
    lines.push("#v(1em)".to_string());
    lines.push("First edition. \\".to_string());
    if !publisher.trim().is_empty() {
        lines.push(format!("{} \\", content(publisher)));
    }
    let body = format!(
        "#set align(left + bottom)\n#set text(size: 0.82em)\n#set par(justify: false, first-line-indent: 0pt, leading: 0.5em)\n{}\n",
        lines.join("\n")
    );
    page_wrap(&body)
}

fn gen_dedication_page(text: &str) -> String {
    let body = format!(
        "#set align(center + horizon)\n#text(style: \"italic\")[{}]\n",
        content(text)
    );
    page_wrap(&body)
}

fn gen_dedication_page_raw(body: &str) -> String {
    let inner = render_centered(body);
    let body = format!("#set align(center + horizon)\n#set text(style: \"italic\")\n{inner}\n");
    page_wrap(&body)
}

/// A front page authored by the writer: an optional centred title, then prose.
fn custom_page(body: &str, heading: &str, show_heading: bool) -> String {
    let mut b = String::new();
    b.push_str("#set align(center)\n#v(4em)\n");
    if show_heading && !heading.trim().is_empty() {
        b.push_str(&format!(
            "#text(size: 1.3em, style: \"italic\")[{}]\n#v(2em)\n",
            content(heading)
        ));
    }
    b.push_str("#set align(left)\n#set par(justify: true)\n");
    b.push_str(&render_prose(body));
    page_wrap(&b)
}

// ---- body structure --------------------------------------------------------


#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::{Kind, Project, ROOT};

    fn scratch(tag: &str) -> Project {
        let dir = std::env::temp_dir().join(format!("jqln-book-{}-{}", std::process::id(), tag));
        let _ = std::fs::remove_dir_all(&dir);
        let mut p = Project::create(&dir, "The Salt Road").unwrap();
        let roots: Vec<String> = p.children[ROOT].clone();
        for r in roots {
            p.remove(&r);
        }
        p
    }

    #[test]
    fn build_produces_a_title_page_and_numbered_chapters() {
        let mut p = scratch("build");
        p.book.author = "A. Writer".into();
        let ms = p.insert(ROOT, None, "Manuscript", Kind::Folder);
        let c1 = p.insert(&ms, None, "Chapter One", Kind::Folder);
        let s1 = p.insert(&c1, None, "Opening", Kind::Text);
        p.set_body(&s1, "The road ran west.".into());
        let c2 = p.insert(&ms, None, "Chapter Two", Kind::Folder);
        let s2 = p.insert(&c2, None, "Next", Kind::Text);
        p.set_body(&s2, "Rain by nightfall.".into());

        let doc = build(&mut p);
        assert!(doc.contains("#set document(title: \"The Salt Road\", author: \"A. Writer\")"));
        assert!(doc.contains("Copyright ©"));
        assert!(doc.contains("== Chapter One\n"));
        assert!(doc.contains("== Chapter Two\n"));
        assert!(doc.contains("#set page(numbering: \"1\""));
        assert!(doc.contains(r#"#"The road ran west.""#));
        let _ = std::fs::remove_dir_all(&p.root);
    }

    #[test]
    fn authored_front_matter_wins_over_generated() {
        let mut p = scratch("frontmatter");
        let fm = p.insert(ROOT, None, "Front Matter", Kind::Folder);
        let ded = p.insert(&fm, None, "Dedication", Kind::Text);
        p.set_body(&ded, "For the road.".into());
        let ms = p.insert(ROOT, None, "Manuscript", Kind::Folder);
        let c = p.insert(&ms, None, "One", Kind::Folder);
        p.insert(&c, None, "s", Kind::Text);

        let pages = front_matter(&mut p);
        // Generated title + generated copyright + the authored dedication.
        assert_eq!(pages.len(), 3);
        assert!(pages[2].contains("For the road."));
        let _ = std::fs::remove_dir_all(&p.root);
    }

    fn typst_available() -> bool {
        Command::new("typst").arg("--version").output().map(|o| o.status.success()).unwrap_or(false)
    }

    #[test]
    fn the_generated_document_compiles_with_typst() {
        if !typst_available() {
            eprintln!("skipping: typst not on PATH");
            return;
        }
        let mut p = scratch("compiles");
        p.book.author = "A. Writer".into();
        p.book.subtitle = "a novel".into();
        p.book.dedication = "For everyone who waited.".into();

        let fm = p.insert(ROOT, None, "Front Matter", Kind::Folder);
        let ack = p.insert(&fm, None, "Acknowledgements", Kind::Text);
        p.set_body(&ack, "Thanks to the usual suspects, and to *you*.".into());

        let ms = p.insert(ROOT, None, "Manuscript", Kind::Folder);
        let part = p.insert(&ms, None, "Part One", Kind::Folder);
        let c1 = p.insert(&part, None, "The Salt Flats", Kind::Folder);
        let s1 = p.insert(&c1, None, "Opening", Kind::Text);
        p.set_body(
            &s1,
            "The road out of the flats was **white** and it went on for a *very* long way.\n\n\
             He counted the miles the way you count anything that will not end.\n\n* * *\n\n\
             By nightfall there was rain — the kind that arrives sideways.\n\n\\newpage\n\n\
             ::: center\nAnd then, nothing.\n:::".into(),
        );
        let c2 = p.insert(&part, None, "Chapter 2", Kind::Folder);
        let s2 = p.insert(&c2, None, "Next", Kind::Text);
        p.set_body(&s2, "She had a #hashtag problem and a [bracket] habit. Both survived.".into());

        let outcome = compile_to_file(&mut p).unwrap();
        match outcome {
            Outcome::Pdf { pdf, .. } => assert!(pdf.exists(), "no pdf produced"),
            Outcome::TypstFailed { message, typ } => {
                let src = std::fs::read_to_string(&typ).unwrap();
                panic!("typst rejected the document: {message}\n---\n{src}");
            }
            Outcome::TypstMissing { .. } => unreachable!("typst was reported available"),
        }
        let _ = std::fs::remove_dir_all(&p.root);
    }

    #[test]
    fn compile_writes_a_typ_file_even_without_typst() {
        let mut p = scratch("typ");
        let ms = p.insert(ROOT, None, "Manuscript", Kind::Folder);
        let c = p.insert(&ms, None, "One", Kind::Folder);
        let s = p.insert(&c, None, "s", Kind::Text);
        p.set_body(&s, "Words.".into());

        let outcome = compile_to_file(&mut p).unwrap();
        let typ = match outcome {
            Outcome::Pdf { typ, .. } | Outcome::TypstMissing { typ } | Outcome::TypstFailed { typ, .. } => typ,
        };
        assert!(typ.exists());
        assert!(typ.ends_with("the-salt-road.typ"));
        assert!(std::fs::read_to_string(&typ).unwrap().contains("== Chapter One"));
        let _ = std::fs::remove_dir_all(&p.root);
    }
}

